name: sokrio_assignment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.1
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: ^6.11.1
  retrofit_generator: null
  riverpod_generator: ^3.0.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
